bhtom2/bhtom_common/urls.py
from django.urls import path

from bhtom2.bhtom_common.views import GetDataProductApi, DataListView, ReloadFits, ReloadPhotometry, \
     DeletePointAndRestartProcess, UpdateFits, ReloadPhotometryWithFits, NewsletterView, DataListCompletedView, CommentAPIView,DataListCCDPHOTErrorView, \
     DataListInProgressView, DataListInCalibView, DataListCPCSErrorView, DataListCPCSLimitView, GetReducedDataApi  ,DeleteReduceDatumApiView, \
          DeactivateReduceDatumApiView, DeleteDataProductApiView, GetUsersDetails,ChangeObserversView,GetPhotometryFile

from bhtom_base.bhtom_common.api_router import SharedAPIRootRouter

router = SharedAPIRootRouter()


app_name = 'common'

urlpatterns = [
     path('', DataListView.as_view(), name='list'),
     path('fitsCompleted/', DataListCompletedView.as_view(), name='list_completed'),
     path('ccdphotError/', DataListCCDPHOTErrorView.as_view(), name='list_ccdphot_error'),
     path('inProgress/', DataListInProgressView.as_view(), name='list_in_progress'),
     path('inCalibration/', DataListInCalibView.as_view(), name='list_in_calibration'),
     path('cpcsError/', DataListCPCSErrorView.as_view(), name='list_cpcs_error'),
     path('cpcsLimit/', DataListCPCSLimitView.as_view(), name='list_cpcs_limit'),
     path('reloadFits/', ReloadFits.as_view(), name='reload_fits'),
     path('updateFits/', UpdateFits.as_view(), name='update_fits'),
     path('deletePointAndRestertFits/', DeletePointAndRestartProcess.as_view(), name='reload_s_fits'),
     path('reloadPhotometry/', ReloadPhotometry.as_view(), name='reload_photometry'),
     path('reloadPhotometryWithFits/', ReloadPhotometryWithFits.as_view(), name='reload_photometry_fits'),
     path('api/data/', GetDataProductApi.as_view(), name='data_api'),
     path('api/deleteDataProduct/', DeleteDataProductApiView.as_view()),
     path('api/reducedDatum/', GetReducedDataApi.as_view(), name='reduced_datum'),
     path('api/deleteReducedDatum/', DeleteReduceDatumApiView.as_view()),
     path('api/deactivateReducedDatum/',DeactivateReduceDatumApiView.as_view()),
     path('newsletter/', NewsletterView.as_view(), name='newsletter'),
     path('api/comments/', CommentAPIView.as_view()),
     path('api/users/',GetUsersDetails.as_view()),
     path('api/changeObservers/', ChangeObserversView.as_view()),
     path('api/downloadPhotometryFile/', GetPhotometryFile.as_view()),
]

bhtom2/bhtom_dataproducts/urls.py
from django.urls import path
from bhtom2.bhtom_dataproducts.views import FitsUploadAPIView, DataProductUploadView, DataProductListAllView, \
    DataProductListUserView, \
    DataProductGroupListView, DataProductGroupCreateView, DataProductGroupDetailView, photometry_download, \
    DataDetailsView, CpcsArchiveData, CalibrationLogDownload, DataProductDeleteView, download_archive_photometry,  CpcsCatalogData

app_name = 'bhtom2.bhtom_dataproducts'
urlpatterns = [
    path('upload/', FitsUploadAPIView.as_view(), name='upload'),
    path("upload-data-ui/", DataProductUploadView.as_view(), name="upload_data_ui"),
    path('data-all/', DataProductListAllView.as_view(), name='list_all'),
    path('data-user/', DataProductListUserView.as_view(), name='list_user'),
    path('data/group/list/', DataProductGroupListView.as_view(), name='group-list'),
    path('data/group/create/', DataProductGroupCreateView.as_view(), name='group-create'),
    path('data/group/<str:name>/', DataProductGroupDetailView.as_view(), name='group-detail'),
    path('download/photometry/<int:id>/', photometry_download.as_view(), name='photometry_download'),
    path('data/<int:pk>/', DataDetailsView.as_view(), name='dataproduct-details'),
    path('delete/<int:pk>/', DataProductDeleteView.as_view(), name='delete'),
    path('cpcs_data', CpcsArchiveData.as_view(), name='list_cpcs'),
    path('download/archive-photometru/<int:id>', download_archive_photometry.as_view(), name='download_archive_photometry'),
    path('cpcs-catalogs', CpcsCatalogData.as_view(), name='cpcs_catalogs'),
    path('download/calibrationLog/<int:id>', CalibrationLogDownload.as_view(), name='calibration_log_download')
]

bhtom2/bhtom_docsbot/urls.py
from django.urls import path
from .views import chat_start, chat_message

urlpatterns = [
    path("chat/start",  chat_start),
    path("chat/start/", chat_start),
    path("chat/message",  chat_message),
    path("chat/message/", chat_message),
]

bhtom2/bhtom_targets/urls.py
from django.urls import path

from bhtom_base.bhtom_targets.views import TargetAddRemoveGroupingView, TargetDeleteView, \
    TargetExportView, TargetGroupingCreateView, TargetGroupingDeleteView, TargetGroupingView, TargetNameSearchView
from .rest.views import CleanTargetListCache, GetTargetListApi, CleanTargetDetailsCache, TargetCreateApi, TargetDownloadHEDataApiView, \
    TargetUpdateApi, TargetDeleteApi, GetPlotsApiView, TargetDownloadRadioDataApiView, TargetDownloadPhotometryDataApiView, GetDownloadedTargetListApi,\
        GetTargetsGroups, GetTargetsFromGroup

from .views import TargetCreateView, TargetDownloadHEDataView, TargetUpdateView, TargetGenerateTargetDescriptionLatexView, TargetImportView, \
    TargetDownloadPhotometryStatsLatexTableView, TargetListImagesView, TargetDownloadPhotometryDataView, \
    TargetDownloadRadioDataView, TargetMicrolensingView, TargetListView, UpdateReducedDatum, TargetNotFoundView, TargetAddNewGroupingView, \
        TargetDetailView

from bhtom_base.bhtom_common.api_router import SharedAPIRootRouter

router = SharedAPIRootRouter()
# router.register(r'targets', TargetViewSet, 'targets')
# router.register(r'targetextra', TargetExtraViewSet, 'targetextra')
# router.register(r'targetname', TargetNameViewSet, 'targetname')

app_name = 'targets'

urlpatterns = [
     path('cleanTargetListCache/', CleanTargetListCache.as_view()),
     path('cleanTargetDetailCache/', CleanTargetDetailsCache.as_view()),
     path('getTargetList/', GetTargetListApi.as_view()),
     path('createTarget/', TargetCreateApi.as_view()),
     path('updateTarget/<str:name>/', TargetUpdateApi.as_view()),
     path('deleteTarget/', TargetDeleteApi.as_view()),
     path('get-plots/', GetPlotsApiView.as_view()),
     path('get-downloaded-target-list/', GetDownloadedTargetListApi.as_view()),
     path('download-photometry/', TargetDownloadPhotometryDataApiView.as_view()),
     path('download-radio/', TargetDownloadRadioDataApiView.as_view()),
     path('download-high-energy/', TargetDownloadHEDataApiView.as_view()),
     path('target-groups/', GetTargetsGroups.as_view()),
     path('targets-from-group/', GetTargetsFromGroup.as_view()),
     path('target_not_found/', TargetNotFoundView.as_view(), name='target_not_found'),
     path('', TargetListView.as_view(), name='list'),
     path('', TargetListView.as_view(), name='targets'),
     path('create/', TargetCreateView.as_view(), name='create'),
     path('<int:pk>/update/', TargetUpdateView.as_view(), name='update'),
     path('<str:name>/update/', TargetUpdateView.as_view(), name='update'),
     path('<int:pk>/delete/', TargetDeleteView.as_view(), name='delete'),
     path('import/', TargetImportView.as_view(), name='import'),
     path('export/', TargetExportView.as_view(), name='export'),
     path('targetgrouping/', TargetGroupingView.as_view(), name='targetgrouping'),
     path('targetgrouping/<int:pk>/delete/', TargetGroupingDeleteView.as_view(), name='delete-group'),
     path('targetgrouping/create/', TargetGroupingCreateView.as_view(), name='create-group'),
     path('add-remove-grouping/', TargetAddRemoveGroupingView.as_view(), name='add-remove-grouping'),
     path('add-new-grouping/', TargetAddNewGroupingView.as_view(), name='add-new-grouping'),
     path('name/<str:name>', TargetNameSearchView.as_view(), name='name-search'),
     path('<int:pk>/generate-target-description-latex/', TargetGenerateTargetDescriptionLatexView.as_view(),
         name='generate_target_description_latex'),
     path('<str:name>/generate-target-description-latex/', TargetGenerateTargetDescriptionLatexView.as_view(),
         name='generate_target_description_latex'),
     path('<int:pk>/download-photometry-stats-latex', TargetDownloadPhotometryStatsLatexTableView.as_view(),
         name='download_photometry_stats_latex'),
     path('import/', TargetImportView.as_view(), name='import'),
     path('images/', TargetListImagesView.as_view(), name='images'),
     path('<int:pk>/download-photometry', TargetDownloadPhotometryDataView.as_view(), name='download_photometry_data'),
     path('<str:name>/download-photometry', TargetDownloadPhotometryDataView.as_view(),
         name='download_photometry_data'),
     path('<int:pk>/download-radio', TargetDownloadRadioDataView.as_view(), name='download_radio_data'),
     path('<str:name>/download-radio', TargetDownloadRadioDataView.as_view(), name='download_radio_data'),
     path('<int:pk>/download-high-energy', TargetDownloadHEDataView.as_view(), name='download_high_energy'),
     path('<str:name>/download-high-energy', TargetDownloadHEDataView.as_view(), name='download_high_energy'),
     path('<int:pk>/microlensing',
         TargetMicrolensingView.as_view(template_name='bhtom_targets/target_microlensing.html'),
         name="microlensing_model"),
     path('<int:pk>/microlensing_parallax',
         TargetMicrolensingView.as_view(template_name='bhtom_targets/target_microlensing_parallax.html'),
         name="microlensing_parallax_model"),

     path('<int:pk>/', TargetDetailView.as_view(template_name='bhtom_targets/target_detail.html'),
         name='detail'),
     path('<str:name>/', TargetDetailView.as_view(template_name='bhtom_targets/target_detail.html'),
         name='detail'),
     path('<int:pk>', TargetDetailView.as_view(template_name='bhtom_targets/target_detail.html'),
         name='detail'),
     path('<str:name>', TargetDetailView.as_view(template_name='bhtom_targets/target_detail.html'),
         name='detail'),

     path('update-reduced-data/<int:pk>', UpdateReducedDatum.as_view(), name='update-reduced-data'),

]

bhtom2/urls.py
from django.urls import path, include
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from django.conf.urls.static import static
from bhtom2.bhtom_targets.views import TargetPublicDetailView
from bhtom2.bhtom_observatory.views import ObservatoryPublicList
from bhtom2.bhtom_observatory.views import ObservatoryPublicDetailView
from settings import settings
from bhtom2.views import BrokerQueryListView
from bhtom2.prometheus_metrics import custom_metrics

schema_view = get_schema_view(
    openapi.Info(
        title="BhTom",
        default_version='v2',
        description="Black Hole Tom",
        contact=openapi.Contact(email="akrawczyk@akond.com"),
    ),
    public=False,
    url=settings.BHTOM_URL
)
urlpatterns = [
    path('swagger/', schema_view.with_ui(cache_timeout=0), name='schema-json'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('targets/', include('bhtom2.bhtom_targets.urls', namespace='bhtom_targets')),
    path('calibration/', include('bhtom2.bhtom_calibration.urls', namespace='bhtom_calibration')),
    path('catalogs/', include('bhtom2.bhtom_catalogs.urls', namespace='bhtom_catalogs')),
    path('proposals/', include('bhtom2.bhtom_observations.urls', namespace='bhtom_proposals')),
    path('observatory/', include('bhtom2.bhtom_observatory.urls', namespace='bhtom_observatory')),
    path('dataproducts/', include('bhtom2.bhtom_dataproducts.urls', namespace='bhtom_dataproducts')),
    path('common/', include('bhtom2.bhtom_common.urls', namespace='bhtom_common')),
    path('', include('bhtom_base.bhtom_common.urls')),
    path('', include('bhtom_custom_registration.bhtom_registration.registration_flows.approval_required.urls',
                     namespace='registration')),
    path('alerts/query/list/', BrokerQueryListView.as_view(template_name='bhtom_alerts/brokerquery_list.html'),
         name='alerts:list'),
    path('', include('django_prometheus.urls')),
    path('metrics/', custom_metrics, name='custom_metrics'),
    # path("public/target/<str:identifier>",TargetPublicDetailView.as_view(template_name="bhtom_targets/target_public_detail.html")),
    # path("public/target/<str:identifier>/",TargetPublicDetailView.as_view(template_name="bhtom_targets/target_public_detail.html")),
    path(
        "public/targets/<int:pk>/",
        TargetPublicDetailView.as_view(template_name="bhtom_targets/target_public_detail.html"),
    ),
    path(
        "public/targets/<int:pk>",
        TargetPublicDetailView.as_view(template_name="bhtom_targets/target_public_detail.html"),
    ),
        path(
        "public/targets/<str:identifier>/",
        TargetPublicDetailView.as_view(template_name="bhtom_targets/target_public_detail.html"),
    ),
    path(
        "public/targets/<str:identifier>",
        TargetPublicDetailView.as_view(template_name="bhtom_targets/target_public_detail.html"),
    ),
    path("public/observatory/",ObservatoryPublicList.as_view()),
    path("public/observatory/<str:identifier>",ObservatoryPublicDetailView.as_view(), name="public_obs_details"),
    path('captcha/', include('captcha.urls')),
    path('select2/', include('django_select2.urls')),
    path("", include("bhtom2.bhtom_docsbot.urls")),  # mounts /chat/start/ and /chat/message/

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bhtom2/bhtom_docsbot/models.py
from django.db import models

# Create your models here.

bhtom2/bhtom_catalogs/forms.py
from django import forms
from .utils import get_harvesters

class CatalogQueryForm(forms.Form):
    """
    Form used for catalog harvesters ``CatalogQueryView``.
    """
    term = forms.CharField()
    service = forms.ChoiceField(choices=[])

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['service'].choices = [(name, name) for name in get_harvesters()]

bhtom2/bhtom_catalogs/views.py
from django.views.generic.edit import FormView
from django.urls import reverse
from urllib.parse import urlencode
from django.core.exceptions import ValidationError
import requests
from django.conf import settings
import json
from django_guid import get_guid

from .forms import CatalogQueryForm
from bhtom_base.bhtom_catalogs.harvester import MissingDataException
from ..utils.bhtom_logger import BHTOMLogger

logger: BHTOMLogger = BHTOMLogger(__name__, 'Bhtom: bhtom_catalogs.views')


class CatalogQueryView(FormView):
    """
    View for querying a specific catalog.
    """

    form_class = CatalogQueryForm
    template_name = 'bhtom_catalogs/query_form.html'
    

    def form_valid(self, form):
        try:
            term = form.cleaned_data['term']
            service = form.cleaned_data['service']
            post_data = {'terms': term, 'harvester': service}
            header = {"Correlation-ID": get_guid()}

            response = requests.post(
                settings.HARVESTER_URL + '/findTargetWithHarvester/',
                data=post_data,
                headers=header,
                timeout=30,
            )

            if response.status_code == 200:
                self.target = response.json()
                if 'discovery_date' not in self.target or self.target.get('discovery_date') is None:
                    self.target['discovery_date'] = ''
                return super().form_valid(form)

            response_text = response.text or ''
            logger.error(
                f'Harvester request failed. status={response.status_code}, '
                f'service={service}, term={term}, response={response_text}'
            )

            if response.status_code == 400 and 'Target not found' in response_text:
                form.add_error('term', ValidationError(f'Object not found dupa {term}'))
            else:
                form.add_error('term', ValidationError(f'Harvester error {response.status_code}: {response_text}'))
            return self.form_invalid(form)

        except (ValueError, json.JSONDecodeError) as e:
            logger.error(f'Invalid JSON from harvester: {e}')
            form.add_error('term', ValidationError('Error while searching for target'))
            return self.form_invalid(form)

        except requests.RequestException as e:
            logger.error(f'Harvester HTTP error: {e}')
            form.add_error('term', ValidationError('Error while searching for target'))
            return self.form_invalid(form)

        except Exception as e:
            logger.error("Oops something went wrong: " + str(e))
            form.add_error('term', ValidationError(f'Error while searching for target: {e}'))
            return self.form_invalid(form)

    def get_success_url(self):
        """
        Redirects to the ``TargetCreateView``. Appends the target parameters to the URL as query parameters in order to
        autofill the ``TargetCreateForm``, including any additional names returned from the query.
        """
        filtered_target = {
            k: str(v) for k, v in self.target.items() if v not in [None, '', 'None']
        }
        return reverse('targets:create') + '?' + urlencode(filtered_target)

bhtom2/bhtom_mymodule/views.py
from django.shortcuts import render

def mymodule_list(request):
    return render(request, 'bhtom_mymodule/list.html')

def mymodule_details(request):
    return render(request, 'bhtom_mymodule/details.html')

bhtom2/templates/bhtom_dataproducts/dataproduct_list.html
{% extends 'bhtom_common/base.html' %}
{% load bootstrap4 static cache %}
{% block title %} Data Product List {% endblock %}
{% block additional_css %}
<link rel="stylesheet" href="{% static 'bhtom_observations/css/main.css' %}">
<link rel="stylesheet" href="{% static 'bhtom_common/css/main.css' %}">
{% endblock %}
{% block content %}
{% include 'bhtom_dataproducts/partials/js9_scripts.html' %}


<div class="row">
    <div class="col-md-2">
        <form action="" method="get" class="form">
            {% bootstrap_form filter.form %}
            {% buttons %}
            <button type="submit" class="btn btn-primary">
                Filter
            </button>
            <a href="{% url 'bhtom_base.bhtom_dataproducts:list' %}" class="btn btn-secondary" title="Reset">Reset</a>
            {% endbuttons %}
        </form>
    </div>
    <div class="col-md-8 ">
        <ul class="nav nav-tabs" id="tabs">
            <li class="nav-item">
                <span class="nav-link active" data-target="#all" data-toggle="tab">All</span>
            </li>
            <li class="nav-item">
                <span class="nav-link" data-target="#user" data-toggle="tab">Your file</span>
            </li>
        </ul>

        <div class="tab-content">
            <div class="tab-pane active" id="all">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>File</th>
                            <th>Photometry</th>
                            <th>Target</th>
                            <th>Observatory</th>
                            <th>Owner</th>
                            <th>Type</th>
                            <th>Status</th>
                            <th>Details</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for product in object_list %}
                        <tr>
                            <td>{{ product.get_file_name|truncatechars:40 }}</td>
                            {% if product.photometry_data is not None %}
                            <td>
                                <a href="{% url 'bhtom_dataproducts:photometry_download' id=product.id %}">
                                    {{product.photometry_data|truncatechars:40 }}</a>
                            </td>
                            {% else %}
                            <td></td>
                            {% endif %}
                            <td>
                                <a href="{% url 'bhtom_targets:detail' product.target.name %}">
                                    {{product.target.name|truncatechars:40 }}</a>
                            </td>
                            <td>{{ product.observatory }}</td>
                            <td>{{ product.user.first_name }} {{ product.user.last_name }}</td>
                            <td>
                                {% if product.data_product_type %}
                                {{ product.get_type_display }}
                                {% endif %}
                            </td>
                            <td>
                                {% if product.status == "C" %}
                                TO DO
                                {% endif %}
                                {% if product.status == "P" %}
                                IN PROGRESS
                                {% endif %}
                                {% if fits.status == "R" %}
                                    Sent to calibration
                                {% endif %}
                                {% if product.status == "S" %}
                                SUCCESS
                                {% endif %}
                                {% if product.status == "E" %}
                                ERROR
                                {% endif %}
                            </td>
                    
                            {% if product.data_product_type == 'fits_file' or product.data_product_type == 'photometry' %}
                            <td>
                                <a href="{% url 'bhtom_dataproducts:dataproduct-details' pk=product.id %}" title="Show details"
                                    class="btn btn-primary">Detail</a>
                            </td>
                            {% else %}
                            <td></td>
                            {% endif %}
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="9">
                                No data yet.

                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% if object_list %}
                    {% bootstrap_pagination page_obj extra=request.GET.urlencode %}
            {% endif %}

            </div>
                 
            <div class="tab-pane" id="user">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>File</th>
                            <th>Photometry</th>
                            <th>Target</th>
                            <th>Observatory</th>
                            <th>Owner</th>
                            <th>Type</th>
                            <th>Status</th>
                            <th>Details</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for product in user_list %}

                                <tr>
                                    <td>{{ product.get_file_name|truncatechars:40 }}</td>
                                    {% if product.photometry_data is not None %}
                                    <td>
                                        <a href="{% url 'bhtom_dataproducts:photometry_download' id=product.id %}">
                                            {{product.photometry_data|truncatechars:40 }}</a>
                                    </td>
                                    {% else %}
                                    <td></td>
                                    {% endif %}
                                    <td>
                                        <a href="{% url 'bhtom_targets:detail' product.target.name %}">
                                            {{product.target.name|truncatechars:40 }}</a>
                                    </td>
                                    <td>{{ product.observatory }}</td>
                                    <td>{{ product.user.first_name }} {{ product.user.last_name }}</td>
                                    <td>
                                        {% if product.data_product_type %}
                                        {{ product.get_type_display }}
                                        {% endif %}
                                    </td>
                                    <td>
                                        {% if product.status == "C" %}
                                        TO DO
                                        {% endif %}
                                        {% if product.status == "P" %}
                                        IN PROGRESS
                                        {% endif %}
                                        {% if fits.status == "R" %}
                                            Send to calibration
                                        {% endif %}
                                        {% if product.status == "S" %}
                                        SUCCESS
                                        {% endif %}
                                        {% if product.status == "E" %}
                                        ERROR
                                        {% endif %}
                                    </td>

                                    {% if product.data_product_type == 'fits_file' or product.data_product_type == 'photometry' %}
                                    <td>
                                        <a href="{% url 'bhtom_dataproducts:dataproduct-details' pk=product.id %}" title="Show details"
                                            class="btn btn-primary">Detail</a>
                                    </td>
                                    {% else %}
                                    <td></td>
                                    {% endif %}
                                </tr>

                            {% empty %}
                            <tr>
                                <td colspan="9">
                                    No data yet.
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% if user_list %}
                    {% bootstrap_pagination page_obj extra=request.GET.urlencode %}
                {% endif %}
            </div>
        </div>
    </div>
</div>        
{% endblock %}

bhtom2/templates/bhtom_dataproducts/dataproductgroup_detail.html
{% extends 'bhtom_common/base.html' %}
{% block title %} Data Product Group {{ object.name }} {% endblock %}
{% block content %}
    <h3>{{ object.name }}</h3>
    <form method="POST">
        {% csrf_token %}
        <table class="table table-striped">
            <thead>
            <tr>
                <th><label><input type="checkbox" id="selectPage"
                                  onClick="select_page(this, {{ target_count }})"/></label></th>
                <th>File</th>
                <th>Photometry</th>
                <th>Target</th>
                <th>Type</th>
                <th>Observatory</th>
                <th>Owner</th>
                <th>Status</th>
                <th>Details</th>
                <th>Remove</th>
            </tr>
            </thead>
            <tbody>
            {% for product in object.dataproduct_set.all %}
                <tr>
                    <td><label>
                        <input type="checkbox" name="selected-target" value="{{ target.id }}"
                               onClick="single_select()"/>
                    </label></td>
                    <td><a href="{{ product.data.url }}">{{ product.data.name }}</a></td>
                    <td><input type="checkbox" name="products" id="product{{ product.id }}" value="{{ product.id }}">
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <input type="submit" value="Remove selected" class="btn btn-danger float-right">
        <input type="submit" value="Remove selected" class="btn btn-danger float-right">
    </form>
{% endblock %}

bhtom2/templates/bhtom_dataproducts/dataproductgroup_list.html
{% extends 'bhtom_common/base.html' %}
{% block title %}Data Product Groups{% endblock %}
{% block content %}

    <div class="row">
        <div class="col-md-12">
            <ul class="nav nav-tabs" id="tabs">
                <li class="nav-item">
                    <span class="nav-link active" data-target="#all" data-toggle="tab">All Group</span>
                </li>
                <li class="nav-item">
                    <span class="nav-link" data-target="#user" data-toggle="tab">Your Group</span>
                </li>
            </ul>

            <div class="tab-content">
                <div class="tab-pane active" id="all">

                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Products</th>
                            <th>Created</th>
                            <th>Private</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for group in object_list %}
                            <tr>

                                {% if group.private == False %}
                                    <td>
                                        <a href="{% url 'bhtom_base.bhtom_dataproducts:group-detail' group.id %}">{{ group.name }}</a>
                                    </td>
                                {% else %}
                                    <td>{{ group.name }}</td>
                                {% endif %}
                                <td>{{ group.dataproduct_set.count }}</td>
                                <td>{{ group.created }}</td>
                                <td>{{ group.private }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
                <div class="tab-pane" id="user">
                    <a href="{% url 'bhtom_base.bhtom_dataproducts:group-create' %}" class="btn btn-primary">Create New
                        Group</a>

                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Products</th>
                            <th>Created</th>
                            <th>Private</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for group in user_group %}
                            <tr>
                                <td>
                                    <a href="{% url 'bhtom_base.bhtom_dataproducts:group-detail' group.id %}">{{ group.name }}</a>
                                </td>
                                <td>{{ group.dataproduct_set.count }}</td>
                                <td>{{ group.created }}</td>
                                <td>{{ group.private }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
{% endblock %}