bhtom2/bhtom_common/urls.py
from django.urls import path

from bhtom2.bhtom_common.views import GetDataProductApi, DataListView, ReloadFits, ReloadPhotometry, \
     DeletePointAndRestartProcess, UpdateFits, ReloadPhotometryWithFits, NewsletterView, DataListCompletedView, CommentAPIView,DataListCCDPHOTErrorView, \
     DataListInProgressView, DataListInCalibView, DataListCPCSErrorView, DataListCPCSLimitView, GetReducedDataApi  ,DeleteReduceDatumApiView, \
          DeactivateReduceDatumApiView, DeleteDataProductApiView, GetUsersDetails,ChangeObserversView,GetPhotometryFile

from bhtom_base.bhtom_common.api_router import SharedAPIRootRouter

router = SharedAPIRootRouter()


app_name = 'common'

urlpatterns = [
     path('', DataListView.as_view(), name='list'),
     path('fitsCompleted/', DataListCompletedView.as_view(), name='list_completed'),
     path('ccdphotError/', DataListCCDPHOTErrorView.as_view(), name='list_ccdphot_error'),
     path('inProgress/', DataListInProgressView.as_view(), name='list_in_progress'),
     path('inCalibration/', DataListInCalibView.as_view(), name='list_in_calibration'),
     path('cpcsError/', DataListCPCSErrorView.as_view(), name='list_cpcs_error'),
     path('cpcsLimit/', DataListCPCSLimitView.as_view(), name='list_cpcs_limit'),
     path('reloadFits/', ReloadFits.as_view(), name='reload_fits'),
     path('updateFits/', UpdateFits.as_view(), name='update_fits'),
     path('deletePointAndRestertFits/', DeletePointAndRestartProcess.as_view(), name='reload_s_fits'),
     path('reloadPhotometry/', ReloadPhotometry.as_view(), name='reload_photometry'),
     path('reloadPhotometryWithFits/', ReloadPhotometryWithFits.as_view(), name='reload_photometry_fits'),
     path('api/data/', GetDataProductApi.as_view(), name='data_api'),
     path('api/deleteDataProduct/', DeleteDataProductApiView.as_view()),
     path('api/reducedDatum/', GetReducedDataApi.as_view(), name='reduced_datum'),
     path('api/deleteReducedDatum/', DeleteReduceDatumApiView.as_view()),
     path('api/deactivateReducedDatum/',DeactivateReduceDatumApiView.as_view()),
     path('newsletter/', NewsletterView.as_view(), name='newsletter'),
     path('api/comments/', CommentAPIView.as_view()),
     path('api/users/',GetUsersDetails.as_view()),
     path('api/changeObservers/', ChangeObserversView.as_view()),
     path('api/downloadPhotometryFile/', GetPhotometryFile.as_view()),
]

bhtom2/bhtom_docsbot/urls.py
from django.urls import path
from .views import chat_start, chat_message

urlpatterns = [
    path("chat/start",  chat_start),
    path("chat/start/", chat_start),
    path("chat/message",  chat_message),
    path("chat/message/", chat_message),
]

bhtom2/bhtom_observatory/urls.py
from django.urls import path

from bhtom2.bhtom_observatory.rest.view import GetObservatoryApi, CreateObservatoryApi, UpdateObservatoryApi, \
    GetObservatoryMatrixApi, CreateObservatoryMatrixApi, DeleteObservatoryMatrixApi
from bhtom2.bhtom_observatory.views import CreateObservatory, UpdateObservatory, DeleteObservatory, ObservatoryList, \
    ObservatoryDetailView, DeleteUserObservatory, UpdateUserObservatory, CreateUserObservatory, ObservatoryFavoriteDetailView,get_cameras, get_favorite_cameras

app_name = 'bhtom2.bhtom_observatory'

urlpatterns = [
    path('getObservatoryList/', GetObservatoryApi.as_view()),
    path('createObservatory/', CreateObservatoryApi.as_view()),
    path('updateObservatory/', UpdateObservatoryApi.as_view()),
    path('getFavouriteObservatory/', GetObservatoryMatrixApi.as_view()),
    path('addFavouriteObservatory/', CreateObservatoryMatrixApi.as_view()),
    path('deleteFavouriteObservatory/', DeleteObservatoryMatrixApi.as_view()),

    path('get-cameras/<int:observatory_id>/<int:user_id>/', get_cameras, name='get_cameras'),
    path('get-favorite-cameras/<int:observatory_id>/<int:user_id>/', get_favorite_cameras, name='get_favorite_cameras'),
    path('create/', CreateObservatory.as_view(), name='create'),
    path('<int:pk>/update/', UpdateObservatory.as_view(), name='update'),
    path('<int:pk>/delete/', DeleteObservatory.as_view(), name='delete'),
    path('<int:pk>/', ObservatoryDetailView.as_view(), name='detail'),
    path('<int:pk>/favorite', ObservatoryFavoriteDetailView.as_view(), name='detail-favorite'),
    path('', ObservatoryList.as_view(), name='list'),
    path('instrument/create/', CreateUserObservatory.as_view(), name='userObservatory_create'),
    path('user/<int:pk>/delete/', DeleteUserObservatory.as_view(), name='userObservatory_delete'),
    path('user/<int:pk>/update/', UpdateUserObservatory.as_view(), name='userObservatory_update'),
]

bhtom2/bhtom_targets/urls.py
from django.urls import path

from bhtom_base.bhtom_targets.views import TargetAddRemoveGroupingView, TargetDeleteView, \
    TargetExportView, TargetGroupingCreateView, TargetGroupingDeleteView, TargetGroupingView, TargetNameSearchView
from .rest.views import CleanTargetListCache, GetTargetListApi, CleanTargetDetailsCache, TargetCreateApi, TargetDownloadHEDataApiView, \
    TargetUpdateApi, TargetDeleteApi, GetPlotsApiView, TargetDownloadRadioDataApiView, TargetDownloadPhotometryDataApiView, GetDownloadedTargetListApi,\
        GetTargetsGroups, GetTargetsFromGroup

from .views import TargetCreateView, TargetDownloadHEDataView, TargetUpdateView, TargetGenerateTargetDescriptionLatexView, TargetImportView, \
    TargetDownloadPhotometryStatsLatexTableView, TargetListImagesView, TargetDownloadPhotometryDataView, \
    TargetDownloadRadioDataView, TargetMicrolensingView, TargetListView, UpdateReducedDatum, TargetNotFoundView, TargetAddNewGroupingView, \
        TargetDetailView

from bhtom_base.bhtom_common.api_router import SharedAPIRootRouter

router = SharedAPIRootRouter()
# router.register(r'targets', TargetViewSet, 'targets')
# router.register(r'targetextra', TargetExtraViewSet, 'targetextra')
# router.register(r'targetname', TargetNameViewSet, 'targetname')

app_name = 'targets'

urlpatterns = [
     path('cleanTargetListCache/', CleanTargetListCache.as_view()),
     path('cleanTargetDetailCache/', CleanTargetDetailsCache.as_view()),
     path('getTargetList/', GetTargetListApi.as_view()),
     path('createTarget/', TargetCreateApi.as_view()),
     path('updateTarget/<str:name>/', TargetUpdateApi.as_view()),
     path('deleteTarget/', TargetDeleteApi.as_view()),
     path('get-plots/', GetPlotsApiView.as_view()),
     path('get-downloaded-target-list/', GetDownloadedTargetListApi.as_view()),
     path('download-photometry/', TargetDownloadPhotometryDataApiView.as_view()),
     path('download-radio/', TargetDownloadRadioDataApiView.as_view()),
     path('download-high-energy/', TargetDownloadHEDataApiView.as_view()),
     path('target-groups/', GetTargetsGroups.as_view()),
     path('targets-from-group/', GetTargetsFromGroup.as_view()),
     path('target_not_found/', TargetNotFoundView.as_view(), name='target_not_found'),
     path('', TargetListView.as_view(), name='list'),
     path('', TargetListView.as_view(), name='targets'),
     path('create/', TargetCreateView.as_view(), name='create'),
     path('<int:pk>/update/', TargetUpdateView.as_view(), name='update'),
     path('<str:name>/update/', TargetUpdateView.as_view(), name='update'),
     path('<int:pk>/delete/', TargetDeleteView.as_view(), name='delete'),
     path('import/', TargetImportView.as_view(), name='import'),
     path('export/', TargetExportView.as_view(), name='export'),
     path('targetgrouping/', TargetGroupingView.as_view(), name='targetgrouping'),
     path('targetgrouping/<int:pk>/delete/', TargetGroupingDeleteView.as_view(), name='delete-group'),
     path('targetgrouping/create/', TargetGroupingCreateView.as_view(), name='create-group'),
     path('add-remove-grouping/', TargetAddRemoveGroupingView.as_view(), name='add-remove-grouping'),
     path('add-new-grouping/', TargetAddNewGroupingView.as_view(), name='add-new-grouping'),
     path('name/<str:name>', TargetNameSearchView.as_view(), name='name-search'),
     path('<int:pk>/generate-target-description-latex/', TargetGenerateTargetDescriptionLatexView.as_view(),
         name='generate_target_description_latex'),
     path('<str:name>/generate-target-description-latex/', TargetGenerateTargetDescriptionLatexView.as_view(),
         name='generate_target_description_latex'),
     path('<int:pk>/download-photometry-stats-latex', TargetDownloadPhotometryStatsLatexTableView.as_view(),
         name='download_photometry_stats_latex'),
     path('import/', TargetImportView.as_view(), name='import'),
     path('images/', TargetListImagesView.as_view(), name='images'),
     path('<int:pk>/download-photometry', TargetDownloadPhotometryDataView.as_view(), name='download_photometry_data'),
     path('<str:name>/download-photometry', TargetDownloadPhotometryDataView.as_view(),
         name='download_photometry_data'),
     path('<int:pk>/download-radio', TargetDownloadRadioDataView.as_view(), name='download_radio_data'),
     path('<str:name>/download-radio', TargetDownloadRadioDataView.as_view(), name='download_radio_data'),
     path('<int:pk>/download-high-energy', TargetDownloadHEDataView.as_view(), name='download_high_energy'),
     path('<str:name>/download-high-energy', TargetDownloadHEDataView.as_view(), name='download_high_energy'),
     path('<int:pk>/microlensing',
         TargetMicrolensingView.as_view(template_name='bhtom_targets/target_microlensing.html'),
         name="microlensing_model"),
     path('<int:pk>/microlensing_parallax',
         TargetMicrolensingView.as_view(template_name='bhtom_targets/target_microlensing_parallax.html'),
         name="microlensing_parallax_model"),

     path('<int:pk>/', TargetDetailView.as_view(template_name='bhtom_targets/target_detail.html'),
         name='detail'),
     path('<str:name>/', TargetDetailView.as_view(template_name='bhtom_targets/target_detail.html'),
         name='detail'),
     path('<int:pk>', TargetDetailView.as_view(template_name='bhtom_targets/target_detail.html'),
         name='detail'),
     path('<str:name>', TargetDetailView.as_view(template_name='bhtom_targets/target_detail.html'),
         name='detail'),

     path('update-reduced-data/<int:pk>', UpdateReducedDatum.as_view(), name='update-reduced-data'),

]

bhtom2/urls.py
from django.urls import path, include
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from django.conf.urls.static import static
from bhtom2.bhtom_targets.views import TargetPublicDetailView
from bhtom2.bhtom_observatory.views import ObservatoryPublicList
from bhtom2.bhtom_observatory.views import ObservatoryPublicDetailView
from settings import settings
from bhtom2.views import BrokerQueryListView
from bhtom2.prometheus_metrics import custom_metrics

schema_view = get_schema_view(
    openapi.Info(
        title="BhTom",
        default_version='v2',
        description="Black Hole Tom",
        contact=openapi.Contact(email="akrawczyk@akond.com"),
    ),
    public=False,
    url=settings.BHTOM_URL
)
urlpatterns = [
    path('swagger/', schema_view.with_ui(cache_timeout=0), name='schema-json'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('targets/', include('bhtom2.bhtom_targets.urls', namespace='bhtom_targets')),
    path('calibration/', include('bhtom2.bhtom_calibration.urls', namespace='bhtom_calibration')),
    path('catalogs/', include('bhtom2.bhtom_catalogs.urls', namespace='bhtom_catalogs')),
    path('proposals/', include('bhtom2.bhtom_observations.urls', namespace='bhtom_proposals')),
    path('observatory/', include('bhtom2.bhtom_observatory.urls', namespace='bhtom_observatory')),
    path('dataproducts/', include('bhtom2.bhtom_dataproducts.urls', namespace='bhtom_dataproducts')),
    path('common/', include('bhtom2.bhtom_common.urls', namespace='bhtom_common')),
    path('', include('bhtom_base.bhtom_common.urls')),
    path('', include('bhtom_custom_registration.bhtom_registration.registration_flows.approval_required.urls',
                     namespace='registration')),
    path('alerts/query/list/', BrokerQueryListView.as_view(template_name='bhtom_alerts/brokerquery_list.html'),
         name='alerts:list'),
    path('', include('django_prometheus.urls')),
    path('metrics/', custom_metrics, name='custom_metrics'),
    # path("public/target/<str:identifier>",TargetPublicDetailView.as_view(template_name="bhtom_targets/target_public_detail.html")),
    # path("public/target/<str:identifier>/",TargetPublicDetailView.as_view(template_name="bhtom_targets/target_public_detail.html")),
    path(
        "public/targets/<int:pk>/",
        TargetPublicDetailView.as_view(template_name="bhtom_targets/target_public_detail.html"),
    ),
    path(
        "public/targets/<int:pk>",
        TargetPublicDetailView.as_view(template_name="bhtom_targets/target_public_detail.html"),
    ),
        path(
        "public/targets/<str:identifier>/",
        TargetPublicDetailView.as_view(template_name="bhtom_targets/target_public_detail.html"),
    ),
    path(
        "public/targets/<str:identifier>",
        TargetPublicDetailView.as_view(template_name="bhtom_targets/target_public_detail.html"),
    ),
    path("public/observatory/",ObservatoryPublicList.as_view()),
    path("public/observatory/<str:identifier>",ObservatoryPublicDetailView.as_view(), name="public_obs_details"),
    path('captcha/', include('captcha.urls')),
    path('select2/', include('django_select2.urls')),
    path("", include("bhtom2.bhtom_docsbot.urls")),  # mounts /chat/start/ and /chat/message/

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bhtom2/bhtom_docsbot/models.py
from django.db import models

# Create your models here.

bhtom2/bhtom_catalogs/forms.py
from django import forms
from .utils import get_harvesters

class CatalogQueryForm(forms.Form):
    """
    Form used for catalog harvesters ``CatalogQueryView``.
    """
    term = forms.CharField()
    service = forms.ChoiceField(choices=[])

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['service'].choices = [(name, name) for name in get_harvesters()]

bhtom2/bhtom_catalogs/views.py
from django.views.generic.edit import FormView
from django.urls import reverse
from urllib.parse import urlencode
from django.core.exceptions import ValidationError
import requests
from django.conf import settings
import json
from django_guid import get_guid

from .forms import CatalogQueryForm
from bhtom_base.bhtom_catalogs.harvester import MissingDataException
from ..utils.bhtom_logger import BHTOMLogger

logger: BHTOMLogger = BHTOMLogger(__name__, 'Bhtom: bhtom_catalogs.views')


class CatalogQueryView(FormView):
    """
    View for querying a specific catalog.
    """

    form_class = CatalogQueryForm
    template_name = 'bhtom_catalogs/query_form.html'
    

    def form_valid(self, form):
        try:
            term = form.cleaned_data['term']
            service = form.cleaned_data['service']
            post_data = {'terms': term, 'harvester': service}
            header = {"Correlation-ID": get_guid()}

            response = requests.post(
                settings.HARVESTER_URL + '/findTargetWithHarvester/',
                data=post_data,
                headers=header,
                timeout=30,
            )

            if response.status_code == 200:
                self.target = response.json()
                if 'discovery_date' not in self.target or self.target.get('discovery_date') is None:
                    self.target['discovery_date'] = ''
                return super().form_valid(form)

            response_text = response.text or ''
            logger.error(
                f'Harvester request failed. status={response.status_code}, '
                f'service={service}, term={term}, response={response_text}'
            )

            if response.status_code == 400 and 'Target not found' in response_text:
                form.add_error('term', ValidationError(f'Object not found dupa {term}'))
            else:
                form.add_error('term', ValidationError(f'Harvester error {response.status_code}: {response_text}'))
            return self.form_invalid(form)

        except (ValueError, json.JSONDecodeError) as e:
            logger.error(f'Invalid JSON from harvester: {e}')
            form.add_error('term', ValidationError('Error while searching for target'))
            return self.form_invalid(form)

        except requests.RequestException as e:
            logger.error(f'Harvester HTTP error: {e}')
            form.add_error('term', ValidationError('Error while searching for target'))
            return self.form_invalid(form)

        except Exception as e:
            logger.error("Oops something went wrong: " + str(e))
            form.add_error('term', ValidationError(f'Error while searching for target: {e}'))
            return self.form_invalid(form)

    def get_success_url(self):
        """
        Redirects to the ``TargetCreateView``. Appends the target parameters to the URL as query parameters in order to
        autofill the ``TargetCreateForm``, including any additional names returned from the query.
        """
        filtered_target = {
            k: str(v) for k, v in self.target.items() if v not in [None, '', 'None']
        }
        return reverse('targets:create') + '?' + urlencode(filtered_target)

bhtom2/bhtom_mymodule/views.py
from django.shortcuts import render

def mymodule_list(request):
    return render(request, 'bhtom_mymodule/list.html')

def mymodule_details(request):
    return render(request, 'bhtom_mymodule/details.html')

bhtom2/templates/bhtom_observatory/observatory_delete.html
{% extends 'bhtom_common/base.html' %}
{% block content %}
{% block title %}Confirm delete{% endblock %}
<form class="form" method="post">
  {% csrf_token %}
  <p>Are you sure you want to delete {{ object.obsName }}?</p>
  <input type="submit" class="btn btn-danger" value="Confirm">
</form>
{% endblock %}

bhtom2/templates/bhtom_observatory/observatory_list.html
{% extends 'bhtom_common/base.html' %}
{% load comments bootstrap4 bhtom_common_extras targets_extras observation_extras dataproduct_extras static cache %}
{% block title %}Observatory {% endblock %}
{% block additional_css %}
    {% comment %} <link rel="stylesheet" href="{% static 'bhtom_common/css/main.css' %}"> {% endcomment %}
    {% comment %} <link rel="stylesheet" href="{% static 'bhtom_targets/css/main.css' %}"> {% endcomment %}
{% endblock %}

{% bootstrap_javascript jquery='True' %}
{% block content %}
<h4>Observatories</h4>
<p>
This page allows managing observatories/instruments registered in BHTOM for automated image processing.
</p><p>
  The <strong>All Observatories</strong> tab lists all telescopes and instruments currently registered in BHTOM.   
If you plan to upload and process your imaging or instrumental photometry data, you must first have the corresponding observatory added to your <strong>Favorite Observatories</strong> list — only then will your submitted data be correctly linked and labeled with your name.  
You can add an observatory to your favorites directly from the <strong>All Observatories</strong> tab, or through a form behind <strong>Add Observatory</strong> button. Use <strong>Add Observatory</strong> link also if it does not yet exist in the system.  
Note that different instruments (e.g. CCD cameras) mounted on the same telescope are treated as separate observatory entries.
</p>
<p>Note that when using scripts for data uploads with API, the observatory (ONAME) should be in your Favorite list. You can also add an observatory to your Favorite list via API. 
</p>

<div class="row">
  <div class="col-md-12">
<ul class="nav nav-tabs" id="tabs" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="user-tab" data-toggle="tab" href="#user" role="tab"
       aria-controls="user" aria-selected="true">Favorite Observatories</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="all-tab" data-toggle="tab" href="#all" role="tab"
       aria-controls="all" aria-selected="false">All Observatories</a>
  </li>
</ul>
<div class="tab-content">
  <div class="tab-pane fade" id="all" role="tabpanel" aria-labelledby="all-tab">
        <a href="{% url 'bhtom_observatory:userObservatory_create' %}" title="Add new observatory" class="btn btn-outline-primary">Add new observatory</a>
          <table id="observatories-table" class="table table-hover sortable">
          <thead>
            <tr>
              <th>Observatory Name</th><th>Lon</th><th>Lat</th><th>Observatory(ONAME)</th><th>Only Instrumental photometry file</th>
              <th>Details</th>
              {% if request.user.is_superuser %}
              <th>Update</th><th>Delete</th>
              {% endif %}
            </tr>
          </thead>
<tbody>
  {% for observatory in observatory_list %}
  <tr>
    <td>{{ observatory.name }}</td>
    <td>{{ observatory.lon }}</td>
    <td>{{ observatory.lat }}</td>
<td>
{% if observatory.id in prefix_obs %}
  <div class="mt-2">
    {% for prefix in prefix_obs|get_item:observatory.id %}
      <div class="d-flex align-items-center mb-1">
        <form action="{% url 'bhtom_observatory:userObservatory_create' %}" method="post" class="mb-0 mr-2">
        {% csrf_token %}
        <input type="hidden" name="quick_add" value="1">  {# <-- disambiguates #}
        <input type="hidden" name="observatory" value="{{ observatory.id }}">
        <input type="hidden" name="camera" value="{{ prefix }}">  {# still the prefix string #}
        <button type="submit" class="btn btn-outline-primary btn-xs px-2 py-0">Add to my list</button>
      </form>
        <span>{{ prefix }}</span>
      </div>
    {% endfor %}
  </div>
{% else %}
  No data available
{% endif %}
</td>
    <td>{{ observatory.calibration_flg }}</td>
    
    <td>
      <a href="{% url 'bhtom_observatory:detail' pk=observatory.id %}" title="Observatory details" class="btn btn-primary">Details</a>
    </td>
    {% if request.user.is_superuser %}
    <td>
      <a href="{% url 'bhtom_observatory:update' pk=observatory.id %}" title="Update observatory" class="btn btn-primary">Edit</a>
    </td>
    <td>
      <a href="{% url 'bhtom_observatory:delete' pk=observatory.id %}" title="Delete observatory" class="btn btn-danger">Delete</a>
    </td>
    {% endif %}
  </tr>
  {% endfor %}
</tbody>
        </table>
  </div>
  <div class="tab-pane fade show active" id="user" role="tabpanel" aria-labelledby="user-tab">
<table id="user-observatories-table" class="table table-hover sortable">
  <thead>
    <tr>
      <th>Observatory Name</th>
      <th>Lon</th>
      <th>Lat</th>
      <th>Observatory (ONAME)</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for observatory in observatory_user_list %}
      <tr>
        <td>{{ observatory.name }}</td>
        <td>{{ observatory.lon }}</td>
        <td>{{ observatory.lat }}</td>

        <td>
          {% with items=prefix_user_obs|get_item:observatory.id %}
            {% if items %}
              {% for entry in items %}
                <div class="d-flex align-items-center mb-1">
                  <form action="{% url 'bhtom_observatory:userObservatory_delete' pk=entry.id %}"
                        method="post" class="mb-0 mr-2">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-outline-danger btn-sm">Remove</button>
                  </form>
                  <span>{{ entry.prefix }}</span>
                </div>
              {% endfor %}
            {% else %}
              No data available
            {% endif %}
          {% endwith %}
        </td>

        <td>
          <a href="{% url 'bhtom_observatory:detail-favorite' pk=observatory.id %}"
             title="Observatory details with favorite cameras"
             class="btn btn-primary btn-sm">
            Details
          </a>
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>
      </div>
  </div>
    </div>
</div>

<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.js"></script>
<script>
  $(document).ready(function() {
      $('#observatories-table').DataTable({
          "paging": false,
          "searching": false
      });
      $('#user-observatories-table').DataTable({
        "paging": false,
        "searching": false
    });
  });
  </script>

{% endblock %}

bhtom2/templates/bhtom_observatory/userObservatory_create.html
{% extends 'bhtom_common/base.html' %}
{% load bootstrap4 static %}
{% block title %}Add observatory{% endblock %}
{% block content %}
{{ users }}
{% if object %}
    <form action="{% url 'bhtom_observatory:userObservatory_update' object.id %}" enctype="multipart/form-data" method="POST">
{% else %}
    <h4> Add a new Observatory to your list.</h4>
    <p>
        Here you can add a new observatory to your list in two ways.<br>
        You can choose an observatory from the list of already registered ones.<br>
        If your observatory is not yet registered you can create a new entry. 
    </p>

    <form action="{% url 'bhtom_observatory:userObservatory_create' %}" enctype="multipart/form-data" method="POST">
{% endif %}

{% csrf_token %}
{% bootstrap_form form %}

{% buttons %}
    {% if object %}
        <button type="submit" class="btn btn-primary" title="Update">Update</button>
    {% else %}
        <button type="submit" class="btn btn-primary" title="Add this Observatory to my list">Add to my list</button>
        <hr>
        <a href="{% url 'bhtom_observatory:create' %}" title="Create new Observatory (if not on the list)" class="btn btn-primary">Create new Observatory</a>
    {% endif %}
{% endbuttons %}
</form>
<script>
    var userId = '{{ request.user.id }}';
</script>
<script src="{% static 'bhtom_observatory/get_cameras.js' %}"></script>
{% endblock %}

bhtom2/templates/bhtom_observatory/userObservatory_delete.html
{% extends 'bhtom_common/base.html' %}
{% block content %}
{% block title %}Confirm delete from your list{% endblock %}
<form class="form" method="post">
  {% csrf_token %}
  <p>Are you sure you want to remove the observatory from your list?</p>
  <input type="submit" class="btn btn-danger" value="Confirm">
</form>
{% endblock %}