bhtom2/bhtom_common/urls.py
from django.urls import path

from bhtom2.bhtom_common.views import GetDataProductApi, DataListView, ReloadFits, ReloadPhotometry, \
     DeletePointAndRestartProcess, UpdateFits, ReloadPhotometryWithFits, NewsletterView, DataListCompletedView, CommentAPIView,DataListCCDPHOTErrorView, \
     DataListInProgressView, DataListInCalibView, DataListCPCSErrorView, DataListCPCSLimitView, GetReducedDataApi  ,DeleteReduceDatumApiView, \
          DeactivateReduceDatumApiView, DeleteDataProductApiView, GetUsersDetails,ChangeObserversView,GetPhotometryFile

from bhtom_base.bhtom_common.api_router import SharedAPIRootRouter

router = SharedAPIRootRouter()


app_name = 'common'

urlpatterns = [
     path('', DataListView.as_view(), name='list'),
     path('fitsCompleted/', DataListCompletedView.as_view(), name='list_completed'),
     path('ccdphotError/', DataListCCDPHOTErrorView.as_view(), name='list_ccdphot_error'),
     path('inProgress/', DataListInProgressView.as_view(), name='list_in_progress'),
     path('inCalibration/', DataListInCalibView.as_view(), name='list_in_calibration'),
     path('cpcsError/', DataListCPCSErrorView.as_view(), name='list_cpcs_error'),
     path('cpcsLimit/', DataListCPCSLimitView.as_view(), name='list_cpcs_limit'),
     path('reloadFits/', ReloadFits.as_view(), name='reload_fits'),
     path('updateFits/', UpdateFits.as_view(), name='update_fits'),
     path('deletePointAndRestertFits/', DeletePointAndRestartProcess.as_view(), name='reload_s_fits'),
     path('reloadPhotometry/', ReloadPhotometry.as_view(), name='reload_photometry'),
     path('reloadPhotometryWithFits/', ReloadPhotometryWithFits.as_view(), name='reload_photometry_fits'),
     path('api/data/', GetDataProductApi.as_view(), name='data_api'),
     path('api/deleteDataProduct/', DeleteDataProductApiView.as_view()),
     path('api/reducedDatum/', GetReducedDataApi.as_view(), name='reduced_datum'),
     path('api/deleteReducedDatum/', DeleteReduceDatumApiView.as_view()),
     path('api/deactivateReducedDatum/',DeactivateReduceDatumApiView.as_view()),
     path('newsletter/', NewsletterView.as_view(), name='newsletter'),
     path('api/comments/', CommentAPIView.as_view()),
     path('api/users/',GetUsersDetails.as_view()),
     path('api/changeObservers/', ChangeObserversView.as_view()),
     path('api/downloadPhotometryFile/', GetPhotometryFile.as_view()),
]

bhtom2/bhtom_docsbot/urls.py
from django.urls import path
from .views import chat_start, chat_message

urlpatterns = [
    path("chat/start",  chat_start),
    path("chat/start/", chat_start),
    path("chat/message",  chat_message),
    path("chat/message/", chat_message),
]

bhtom2/bhtom_targets/urls.py
from django.urls import path

from bhtom_base.bhtom_targets.views import TargetAddRemoveGroupingView, TargetDeleteView, \
    TargetExportView, TargetGroupingCreateView, TargetGroupingDeleteView, TargetGroupingView, TargetNameSearchView
from .rest.views import CleanTargetListCache, GetTargetListApi, CleanTargetDetailsCache, TargetCreateApi, TargetDownloadHEDataApiView, \
    TargetUpdateApi, TargetDeleteApi, GetPlotsApiView, TargetDownloadRadioDataApiView, TargetDownloadPhotometryDataApiView, GetDownloadedTargetListApi,\
        GetTargetsGroups, GetTargetsFromGroup

from .views import TargetCreateView, TargetDownloadHEDataView, TargetUpdateView, TargetGenerateTargetDescriptionLatexView, TargetImportView, \
    TargetDownloadPhotometryStatsLatexTableView, TargetListImagesView, TargetDownloadPhotometryDataView, \
    TargetDownloadRadioDataView, TargetMicrolensingView, TargetListView, UpdateReducedDatum, TargetNotFoundView, TargetAddNewGroupingView, \
        TargetDetailView

from bhtom_base.bhtom_common.api_router import SharedAPIRootRouter

router = SharedAPIRootRouter()
# router.register(r'targets', TargetViewSet, 'targets')
# router.register(r'targetextra', TargetExtraViewSet, 'targetextra')
# router.register(r'targetname', TargetNameViewSet, 'targetname')

app_name = 'targets'

urlpatterns = [
     path('cleanTargetListCache/', CleanTargetListCache.as_view()),
     path('cleanTargetDetailCache/', CleanTargetDetailsCache.as_view()),
     path('getTargetList/', GetTargetListApi.as_view()),
     path('createTarget/', TargetCreateApi.as_view()),
     path('updateTarget/<str:name>/', TargetUpdateApi.as_view()),
     path('deleteTarget/', TargetDeleteApi.as_view()),
     path('get-plots/', GetPlotsApiView.as_view()),
     path('get-downloaded-target-list/', GetDownloadedTargetListApi.as_view()),
     path('download-photometry/', TargetDownloadPhotometryDataApiView.as_view()),
     path('download-radio/', TargetDownloadRadioDataApiView.as_view()),
     path('download-high-energy/', TargetDownloadHEDataApiView.as_view()),
     path('target-groups/', GetTargetsGroups.as_view()),
     path('targets-from-group/', GetTargetsFromGroup.as_view()),
     path('target_not_found/', TargetNotFoundView.as_view(), name='target_not_found'),
     path('', TargetListView.as_view(), name='list'),
     path('', TargetListView.as_view(), name='targets'),
     path('create/', TargetCreateView.as_view(), name='create'),
     path('<int:pk>/update/', TargetUpdateView.as_view(), name='update'),
     path('<str:name>/update/', TargetUpdateView.as_view(), name='update'),
     path('<int:pk>/delete/', TargetDeleteView.as_view(), name='delete'),
     path('import/', TargetImportView.as_view(), name='import'),
     path('export/', TargetExportView.as_view(), name='export'),
     path('targetgrouping/', TargetGroupingView.as_view(), name='targetgrouping'),
     path('targetgrouping/<int:pk>/delete/', TargetGroupingDeleteView.as_view(), name='delete-group'),
     path('targetgrouping/create/', TargetGroupingCreateView.as_view(), name='create-group'),
     path('add-remove-grouping/', TargetAddRemoveGroupingView.as_view(), name='add-remove-grouping'),
     path('add-new-grouping/', TargetAddNewGroupingView.as_view(), name='add-new-grouping'),
     path('name/<str:name>', TargetNameSearchView.as_view(), name='name-search'),
     path('<int:pk>/generate-target-description-latex/', TargetGenerateTargetDescriptionLatexView.as_view(),
         name='generate_target_description_latex'),
     path('<str:name>/generate-target-description-latex/', TargetGenerateTargetDescriptionLatexView.as_view(),
         name='generate_target_description_latex'),
     path('<int:pk>/download-photometry-stats-latex', TargetDownloadPhotometryStatsLatexTableView.as_view(),
         name='download_photometry_stats_latex'),
     path('import/', TargetImportView.as_view(), name='import'),
     path('images/', TargetListImagesView.as_view(), name='images'),
     path('<int:pk>/download-photometry', TargetDownloadPhotometryDataView.as_view(), name='download_photometry_data'),
     path('<str:name>/download-photometry', TargetDownloadPhotometryDataView.as_view(),
         name='download_photometry_data'),
     path('<int:pk>/download-radio', TargetDownloadRadioDataView.as_view(), name='download_radio_data'),
     path('<str:name>/download-radio', TargetDownloadRadioDataView.as_view(), name='download_radio_data'),
     path('<int:pk>/download-high-energy', TargetDownloadHEDataView.as_view(), name='download_high_energy'),
     path('<str:name>/download-high-energy', TargetDownloadHEDataView.as_view(), name='download_high_energy'),
     path('<int:pk>/microlensing',
         TargetMicrolensingView.as_view(template_name='bhtom_targets/target_microlensing.html'),
         name="microlensing_model"),
     path('<int:pk>/microlensing_parallax',
         TargetMicrolensingView.as_view(template_name='bhtom_targets/target_microlensing_parallax.html'),
         name="microlensing_parallax_model"),

     path('<int:pk>/', TargetDetailView.as_view(template_name='bhtom_targets/target_detail.html'),
         name='detail'),
     path('<str:name>/', TargetDetailView.as_view(template_name='bhtom_targets/target_detail.html'),
         name='detail'),
     path('<int:pk>', TargetDetailView.as_view(template_name='bhtom_targets/target_detail.html'),
         name='detail'),
     path('<str:name>', TargetDetailView.as_view(template_name='bhtom_targets/target_detail.html'),
         name='detail'),

     path('update-reduced-data/<int:pk>', UpdateReducedDatum.as_view(), name='update-reduced-data'),

]

bhtom2/urls.py
from django.urls import path, include
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from django.conf.urls.static import static
from bhtom2.bhtom_targets.views import TargetPublicDetailView
from bhtom2.bhtom_observatory.views import ObservatoryPublicList
from bhtom2.bhtom_observatory.views import ObservatoryPublicDetailView
from settings import settings
from bhtom2.views import BrokerQueryListView
from bhtom2.prometheus_metrics import custom_metrics

schema_view = get_schema_view(
    openapi.Info(
        title="BhTom",
        default_version='v2',
        description="Black Hole Tom",
        contact=openapi.Contact(email="akrawczyk@akond.com"),
    ),
    public=False,
    url=settings.BHTOM_URL
)
urlpatterns = [
    path('swagger/', schema_view.with_ui(cache_timeout=0), name='schema-json'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('targets/', include('bhtom2.bhtom_targets.urls', namespace='bhtom_targets')),
    path('calibration/', include('bhtom2.bhtom_calibration.urls', namespace='bhtom_calibration')),
    path('catalogs/', include('bhtom2.bhtom_catalogs.urls', namespace='bhtom_catalogs')),
    path('proposals/', include('bhtom2.bhtom_observations.urls', namespace='bhtom_proposals')),
    path('observatory/', include('bhtom2.bhtom_observatory.urls', namespace='bhtom_observatory')),
    path('dataproducts/', include('bhtom2.bhtom_dataproducts.urls', namespace='bhtom_dataproducts')),
    path('common/', include('bhtom2.bhtom_common.urls', namespace='bhtom_common')),
    path('', include('bhtom_base.bhtom_common.urls')),
    path('', include('bhtom_custom_registration.bhtom_registration.registration_flows.approval_required.urls',
                     namespace='registration')),
    path('alerts/query/list/', BrokerQueryListView.as_view(template_name='bhtom_alerts/brokerquery_list.html'),
         name='alerts:list'),
    path('', include('django_prometheus.urls')),
    path('metrics/', custom_metrics, name='custom_metrics'),
    # path("public/target/<str:identifier>",TargetPublicDetailView.as_view(template_name="bhtom_targets/target_public_detail.html")),
    # path("public/target/<str:identifier>/",TargetPublicDetailView.as_view(template_name="bhtom_targets/target_public_detail.html")),
    path(
        "public/targets/<int:pk>/",
        TargetPublicDetailView.as_view(template_name="bhtom_targets/target_public_detail.html"),
    ),
    path(
        "public/targets/<int:pk>",
        TargetPublicDetailView.as_view(template_name="bhtom_targets/target_public_detail.html"),
    ),
        path(
        "public/targets/<str:identifier>/",
        TargetPublicDetailView.as_view(template_name="bhtom_targets/target_public_detail.html"),
    ),
    path(
        "public/targets/<str:identifier>",
        TargetPublicDetailView.as_view(template_name="bhtom_targets/target_public_detail.html"),
    ),
    path("public/observatory/",ObservatoryPublicList.as_view()),
    path("public/observatory/<str:identifier>",ObservatoryPublicDetailView.as_view(), name="public_obs_details"),
    path('captcha/', include('captcha.urls')),
    path('select2/', include('django_select2.urls')),
    path("", include("bhtom2.bhtom_docsbot.urls")),  # mounts /chat/start/ and /chat/message/

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bhtom2/bhtom_docsbot/models.py
from django.db import models

# Create your models here.

bhtom2/bhtom_catalogs/forms.py
from django import forms
from .utils import get_harvesters

class CatalogQueryForm(forms.Form):
    """
    Form used for catalog harvesters ``CatalogQueryView``.
    """
    term = forms.CharField()
    service = forms.ChoiceField(choices=[])

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['service'].choices = [(name, name) for name in get_harvesters()]

bhtom2/bhtom_common/forms.py
from django import forms

from bhtom_base.bhtom_dataproducts.models import DataProduct


class UpdateFitsForm(forms.ModelForm):

    status_message = forms.CharField(
        label='Status Message', required=False,
        widget=forms.Textarea(attrs={'rows': 1, 'cols': 200}),
    )

    delete_fits = forms.BooleanField(
        label='Delete Fits from disk', required=False,
        initial=False,
    )

    def __init__(self, *args, **kwargs):
        super(UpdateFitsForm, self).__init__(*args, **kwargs)

    class Meta:
        model = DataProduct
        fields = ('status', 'status_message', 'delete_fits')

bhtom2/bhtom_catalogs/views.py
from django.views.generic.edit import FormView
from django.urls import reverse
from urllib.parse import urlencode
from django.core.exceptions import ValidationError
import requests
from django.conf import settings
import json
from django_guid import get_guid

from .forms import CatalogQueryForm
from bhtom_base.bhtom_catalogs.harvester import MissingDataException
from ..utils.bhtom_logger import BHTOMLogger

logger: BHTOMLogger = BHTOMLogger(__name__, 'Bhtom: bhtom_catalogs.views')


class CatalogQueryView(FormView):
    """
    View for querying a specific catalog.
    """

    form_class = CatalogQueryForm
    template_name = 'bhtom_catalogs/query_form.html'
    

    def form_valid(self, form):
        try:
            term = form.cleaned_data['term']
            service = form.cleaned_data['service']
            post_data = {'terms': term, 'harvester': service}
            header = {"Correlation-ID": get_guid()}

            response = requests.post(
                settings.HARVESTER_URL + '/findTargetWithHarvester/',
                data=post_data,
                headers=header,
                timeout=30,
            )

            if response.status_code == 200:
                self.target = response.json()
                if 'discovery_date' not in self.target or self.target.get('discovery_date') is None:
                    self.target['discovery_date'] = ''
                return super().form_valid(form)

            response_text = response.text or ''
            logger.error(
                f'Harvester request failed. status={response.status_code}, '
                f'service={service}, term={term}, response={response_text}'
            )

            if response.status_code == 400 and 'Target not found' in response_text:
                form.add_error('term', ValidationError(f'Object not found dupa {term}'))
            else:
                form.add_error('term', ValidationError(f'Harvester error {response.status_code}: {response_text}'))
            return self.form_invalid(form)

        except (ValueError, json.JSONDecodeError) as e:
            logger.error(f'Invalid JSON from harvester: {e}')
            form.add_error('term', ValidationError('Error while searching for target'))
            return self.form_invalid(form)

        except requests.RequestException as e:
            logger.error(f'Harvester HTTP error: {e}')
            form.add_error('term', ValidationError('Error while searching for target'))
            return self.form_invalid(form)

        except Exception as e:
            logger.error("Oops something went wrong: " + str(e))
            form.add_error('term', ValidationError(f'Error while searching for target: {e}'))
            return self.form_invalid(form)

    def get_success_url(self):
        """
        Redirects to the ``TargetCreateView``. Appends the target parameters to the URL as query parameters in order to
        autofill the ``TargetCreateForm``, including any additional names returned from the query.
        """
        filtered_target = {
            k: str(v) for k, v in self.target.items() if v not in [None, '', 'None']
        }
        return reverse('targets:create') + '?' + urlencode(filtered_target)

bhtom2/bhtom_mymodule/views.py
from django.shortcuts import render

def mymodule_list(request):
    return render(request, 'bhtom_mymodule/list.html')

def mymodule_details(request):
    return render(request, 'bhtom_mymodule/details.html')

bhtom2/bhtom_observations/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden
from django.views.generic import ListView, DetailView
from guardian.shortcuts import get_objects_for_user

from bhtom2.utils.bhtom_logger import BHTOMLogger
from bhtom_base.bhtom_observations.models import Proposal

logger: BHTOMLogger = BHTOMLogger(__name__, 'Bhtom: bhtom_observation-views')


class ProposalListView(LoginRequiredMixin, ListView):
    template_name = 'bhtom_observations/proposal_list.html'
    strict = False
    model = Proposal

    def get_queryset(self):
        if self.request.user.has_perm('bhtom_observations.view_proposal'):
            return Proposal.objects.all()
        else:
            return get_objects_for_user(self.request.user, Proposal)


class ProposalDetailView(DetailView):
    template_name = 'bhtom_observations/proposal_detail.html'
    strict = False
    model = Proposal

    def get_object(self, queryset=None):
        obj = super(ProposalDetailView, self).get_object(queryset=queryset)
        if self.request.user.has_perm('bhtom_observations.view_proposal'):
            return obj
        elif self.request.user in obj.users:
            raise obj
        else:
            return HttpResponseForbidden()

bhtom2/templates/bhtom_targets/target_form.html
{% extends 'bhtom_common/base.html' %}
{% load bootstrap4 static %}
{% block title %}New Target{% endblock %}
{% block content %}
    {% if not object %}
        <h3>Create a Target</h3>
    {% else %}
        <h3> Update {{ object.name }}</h3>
    {% endif %}

    <form method="post" class="form">

        {% csrf_token %}
        {% bootstrap_form form %}
        <div id="alias-form-container">
            <h3>Aliases</h3>
            {#    {% bootstrap_formset names_form %}#}
            {{ names_form.management_form }}
            {% for form in names_form %}
                <div class="alias-formset row">
                    <div class="col-md-4">
                        {% bootstrap_field form.source_name %}
                    </div>
                    <div class="col-md-4">
                        {% bootstrap_field form.name %}
                    </div>
                    <div class="col-md-4">
                        {% bootstrap_field form.url %}
                    </div>
                    <div class="col-md-2 align-self-end">
                        <button class="btn btn-danger btn-delete" style="margin-bottom: 1rem;">Delete Alias Field</button>
                    </div>
                </div>
            {% endfor %}

            <button id="add-alias-form" class="btn btn-secondary">Add new alias</button>
        </div>
        <!-- <h3>Tags</h3> -->

        <br>
        {% buttons %}
            {% if not object %}
                <button type="submit" id="submit-btn" formaction="{% url 'bhtom_targets:create' %}"
                        class="btn btn-primary">
                    Submit
                </button>
            {% else %}
                <button type="submit" id="save-btn" formaction="{% url 'bhtom_targets:update' pk=object.id %}"
                        class="btn btn-primary">Save
                </button>
                <a href="{% url 'bhtom_targets:detail' pk=object.id %}" class="btn btn-primary" title="Back">Back</a>
            {% endif %}
        {% endbuttons %}

    </form>
{% endblock %}

{% block extra_javascript %}
    <script type="text/JavaScript" src="{% static 'bhtom_targets/js/add_alias_formset.js' %}"></script>
{% endblock %}

bhtom2/templates/bhtom_targets/target_list.html
{% extends 'bhtom_common/base.html' %}
{% load bootstrap4 targets_extras bhtom_targets_extras dataproduct_extras cache static %}
{% block title %}Targets{% endblock %}
{% block content %}
    <div class="row">
        <!-- target list is being displayed for the whole range of the page -->
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-12">
                    <span class="float-right" style="color: rgb(43, 158, 203);">
                        {{ target_count }} {% if target_count == 1 %}Target{% else %}Targets{% endif %} &nbsp;
                        <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton"
                                data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                          Create Targets
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                          <a class="dropdown-item" href="{% url 'targets:create' %}" title="Create a Target">Create a Target</a>
                          <a class="dropdown-item" href="{% url 'targets:import' %}" title="Import Targets">Import Targets</a>
                          <a class="dropdown-item" href="{% url 'bhtom2.bhtom_catalogs:query' %}"
                             title="Catalog Search">Catalog Search</a>
                        </div>

                        <button type="button" class="btn btn-primary" onclick="export_selected_targets()">Export Selected Targets</button>

                  </span>
                </div>
            </div>
            <div style="padding-bottom: 20px;"></div>
            {% select_target_js %}
            {% cache 86400 target_distribution_cache query_string using="targetList" %}
                {% target_distribution filter.qs %}
            {% endcache %}

            <label id="displaySelected"></label>
            <button id="optionSelectAll" type="button" class="btn btn-link"
                    onClick="select_all({{ target_count }})"></button>
            <form id="grouping-form" action="{% url 'targets:add-remove-grouping' %}" method="POST">
                {% csrf_token %}
                <div class="form-group d-flex justify-content-end align-items-baseline">
                    <label>Add/Remove from grouping</label>
                    <select name="grouping" class="form-control w-25 ml-1">
                        {% for grouping in groupings %}
                            <option value="{{ grouping.id }}">{{ grouping.name }}</option>
                        {% endfor %}
                    </select>

                    <input type="hidden" value="{{ query_string }}" name="query_string">
                    <input type="hidden" value="False" id="isSelectAll" name="isSelectAll">
                    <button type="submit" class="btn btn-outline-primary ml-1" name="add">Add</button>
                    <button type="submit" class="btn btn-outline-primary ml-1" name="move">Move</button>
                    <button type="submit" class="btn btn-outline-danger ml-1" name="remove">Remove</button>
                </div>
                {% if query_string == '' %}
                   {% target_table object_list query_string %}
                {% else %}
                    {% target_table object_list query_string %}
                {% endif %}
            </form>
            <!-- closing table and form to add targets -->

        </div>
    </div>

    <!-- filters below the table (new row) -->
    <div class="row">
        <div class="col-md-12">

            <h4>Filtering</h4>
            {{ filter.fields }}
            <div class="col-md-4">
                <form action="" method="get" class="form">
                    {% bootstrap_form filter.form exclude='tweet,epoch,pm_ra,pm_dec,distance,distance_err,dont_update_me,has_optical,has_infrared,has_radio,has_xray,has_gamma,has_polarimetry' %}
                    <h6>Data Types</h6>
                    {% bootstrap_field filter.form.has_optical %}
                    {% bootstrap_field filter.form.has_infrared %}
                    {% bootstrap_field filter.form.has_radio %}
                    {% bootstrap_field filter.form.has_xray %}
                    {% bootstrap_field filter.form.has_gamma %}
                    {% bootstrap_field filter.form.has_polarimetry %}
                    {% buttons %}
                        <button type="submit" class="btn btn-primary">
                            Filter
                        </button>
                        <a href="{% url 'targets:list' %}" class="btn btn-secondary" title="Reset">Reset</a>
                        <button type="submit" formaction="{% url 'targets:export' %}" id="invisible-export-button"
                                style="display:none"></button>
                    {% endbuttons %}
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block javascript %}
    <script src="https://code.jquery.com/jquery-3.6.1.min.js"
            integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function () {
            var table = $('.table').DataTable();
            $('#DataTables_Table_0_filter').hide();
    
            // Function to set color and text for pagination buttons
            function setPaginationStyle() {
                var buttons = document.querySelectorAll('.paginate_button');
                for (var i = 0; i < buttons.length; i++) {
                    buttons[i].style.setProperty('color', '#fff', 'important');
                }
    
                // Change the text and color for the previous button
                var prev_button = document.querySelector('.paginate_button.previous');
                if (prev_button) {
                    prev_button.textContent = '<<';
                    prev_button.style.setProperty('color', '#fff', 'important');
                }
    
                // Change the text and color for the next button
                var next_button = document.querySelector('.paginate_button.next');
                if (next_button) {
                    next_button.textContent = '>>';
                    next_button.style.setProperty('color', '#fff', 'important');
                }
            } 
    
            // Check if the DataTables table is empty
            if (table.data().count() > 0) {
                // Initial style setup
                setPaginationStyle();
          
                // Event delegation for pagination buttons
                $('.dataTables_paginate').on('click', '.paginate_button', function () {
                    // Set the color immediately on click
                    $(this).css('color', '#fff !important');
                });
          
                // After each page change, reapply the style
                table.on('draw', function () {
                    setPaginationStyle();
                });
            }

            $('#id_cone_search').on('input', function() {
                var inputVal = $(this).val().trim();
                var isValid = /^[\w\s]+,\s*[\w\s]+,\s*[\w\s]+$/g.test(inputVal);
                if (!isValid) {
                    $(this).css('color', 'red');
                } else {
                    $(this).css('color', ''); // Reset color
                }
            });
            $('#id_target_cone_search').on('input', function() {
                var inputVal = $(this).val().trim();
                var isValid = /^[\w\s]+,\s*[\w\s]+$/g.test(inputVal);
                if (!isValid) {
                    $(this).css('color', 'red');
                } else {
                    $(this).css('color', ''); // Reset color
                }
            });
        });
    </script>
{% endblock %}

bhtom2/templates/bhtom_targets/target_list_images.html
{% extends 'bhtom_common/base.html' %}
{% load comments bootstrap4 bhtom_common_extras targets_extras observation_extras dataproduct_extras static cache %}
{% block title %}Targets images{% endblock %}

{% block content %}

    <!-- filters  -->
    {{ filter.fields }}
    <div class="col-md-10">
        <form action="" method="get" class="form">
            {% bootstrap_form filter.form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary">
                    Filter
                </button>
                <a href="{% url 'targets:list' %}" class="btn btn-secondary" title="Reset">Reset</a>
                <button type="submit" formaction="{% url 'targets:export' %}" id="invisible-export-button"
                        style="display:none"></button>
            {% endbuttons %}
        </form>
    </div>

    <div class="row">
        
        <div class="col-md-10">
            <!-- this will only plot something if the form is submitted, can be empty to give a whole list -->
            {% if filter.form.is_bound %}
                <label>Found targets: {{target_count}}</label>
                <table class="table table-hover">
                    <tbody>
                    {% for target in object_list %}
                        <tr>
                            <td>
                                {{ target.name }} {{ target.ra }} {{ target.dec }}
                                {% photometry_for_target_icon target %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% endif %}

        </div>
    </div>
{% endblock %}
{% block javascript %}
    <script src="https://code.jquery.com/jquery-3.6.1.min.js"
            integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script>

        $(document).ready(function () {
            $('.table').DataTable();
            $('#DataTables_Table_0_filter').hide();
        });
    </script>
{% endblock %}